app:
  restart: always
  build: ./app
  volumes:
    - /app/static
  environment:
    - PORT=${PORT_APP_INTERNAL}
  expose:
    - ${PORT_APP_EXTERNAL}
  ports:
    - "${PORT_APP_EXTERNAL}:${PORT_APP_INTERNAL}"