web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  environment: 
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
