app:
  restart: always
  build: ./app
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /app/static
  environment:
    - PORT=8000

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
